[package]
name = "pkg-validator"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
clap = { version = "4.0", features = ["derive"] }
bincode = "2.0"
sha2 = "0.10"
asset_manager = { path = "../../asset-manager" }
