

[workspace]
resolver = "3"
members = [
	"audio-backend",
	"audio-system",
	"resonance-cxx",
	"engine-core",
	"asset-manager",
	"app-android",
	"integration-tests",
	"tools/asset-packer",
	"tools/sfx-convert",
	"tools/asset-utils",
	"tools/pkg-validator",
	"resonance-audio-engine"
]
