[tasks.generate-bindings]
description = "Generate FFI bindings using bindgen via build.rs"
command = "cargo"
args = ["build", "-p", "resonance-ffi"]

[tasks.patch-bindings]
description = "Patch generated bindings to use unsafe extern blocks"
script = ["pwsh ./scripts/patch_bindings.ps1"]

[tasks.ffi-workflow]
description = "Generate and patch FFI bindings, then build the project"
dependencies = ["generate-bindings", "patch-bindings"]
command = "cargo"
args = ["build"]
