[package]
name = "integration-tests"
version = "0.1.0"
edition = "2021"

[dependencies]
audio-backend = { path = "../audio-backend" }
resonance-cxx = { path = "../resonance-cxx" }
cxx = "1.0.168"
cpal = "0.15"
serial_test = "2.0"

[features]
real-audio-tests = []