[package]
name = "asset-packer"
version = "0.1.0"
edition = "2021"

[dependencies]
bincode = { version = "2.0", features = ["derive"] }
sha2 = "0.10"
walkdir = "2.3"
symphonia = { version = "0.5.4", features = ["all"] }

[dependencies.asset_manager]
path = "../../asset-manager"
